apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: {{ .Values.proxyGroup.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ingress
  replicas: {{ .Values.proxyGroup.replicas }}
