client_id: ENC[AES256_GCM,data:ax6G2t6mfLxNGTij37NDz8o=,iv:SQvCxFvKKM4tAN+GYSYvcWcS8jr+5H+W+HHm6xOWlxw=,tag:GDJ1pDwwHksoegQQ/KOkVA==,type:str]
client_secret: ENC[AES256_GCM,data:qyRFx62ktbP4Ig/eYc+oeJNwaH57Jrv3xmnsh9dT6WGGGX1U9n6tYtG9t26612IPZQjruN6DrBDYp893qN0qBA==,iv:y0yGfNjH/nGC0GGAHhM3CkC/iF5pZOmScl8nKrHZd1Y=,tag:iK1qlQg0hry/INdZa8Kspg==,type:str]
sops:
    age:
        - recipient: age10n49wavc547hh36jhvhg2dehn68vlp38v5jlwf5s6pelrjd4v57symt274
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQUZLcDdoU0lqOEZmU0Nk
            VHhqOUpLNG9QSm9jNHpKWjlhdFprNlAvK0JnCnFsZWM1S1BiVkxVbS9KNmRWQ296
            TzkyWnFucThaaG5rZzdpU3BGa0pZTUEKLS0tIFVqRGV5QXRsTHpQNm9GRVFZc2dl
            QU5mUnF4ZlBjOVM5aUw3c3RsdVdGNlkKTl5b72gf99oOwkjh1w5DaAXwekPkSVe4
            etL18pazVyGh+5evHsuOcbqUEJP41BK8f8xTLHS4Cv1NeqKoYcTr8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qqw5xfh44mz2s4yacr989elxvwgkzpl3l0dwt4a8y6smqj2xycvs3svtcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRXlwT1hEbjJ5eGlEMisr
            NDMrM0lVc1ZpZHpXeWJySUIrL0l4d3QzSFJVCkxjTExCWjFDN1NEZmM2ODdHWldw
            WG1MVDYwdkh0RzBNangxRjloY3JSN0kKLS0tIGMvbk14U1ZGWWZzbmxIeENuVHRi
            K3hwRURsMUl1amlGbzFYUEROclR5MVUKjez358LMXNfv9yE5sfpg9P1BVOjcpjf5
            wcwZHElARujMfUqlltOEx+D+ycrKsFYqMDkHZXQMFrBfnP84dgFSsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13fk0y8df50wdvpkwu3yf2jdhz6kl74rfvlwvg4p3v6e5hg7negkslfy689
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRE5UQUM4QWVjVW9hNmFG
            UVNKTFpXUmVpU0RQOG5rWGc0akZidld6blNZCm5jeUw2V3lCSnlHUVhESTJnT01i
            M0JkMk1INXNoSWpLK0dlTnBKb3h0OE0KLS0tIFI5YXZLRWo0VGZXdGg3N216MzN0
            TGVINWQ5VUlPN202MVI4aUtsVC9NaTQKq3u58oKe9QyJ/pGyia58AXNtHp0hvPYZ
            ckEtybPrymyyNDLK8073QO36PAcVdu5zu5GdYuQtVvBFBmKE4CvkQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T18:26:26Z"
    mac: ENC[AES256_GCM,data:vHL8vBHfmoAa17pgivpfWrJSt8wPflOf6psJQvm1+5oCft0D7vxwewWm1SYBh3BHoyn9xAgIb3N1mxUfZiFOup08acqG3oSofWOtIZUSa5i4/rJ2BPm/7q78Ayd2v40f4ysDMNL4dA6LPYT7fCILNxNWOumrEmWq9w8SefBbecI=,iv:3Npqz2xBFUZYtNKGr5yzvSbmS6pvbuuhI/LlD+9ngQY=,tag:GdvS3zFsldEEUnmjtZvgQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
