repositories:
  - name: nvdp
    url: https://nvidia.github.io/k8s-device-plugin
  - name: nfd
    oci: true
    url: registry.k8s.io/nfd/charts
  - name: intel-resource-drivers-for-kubernetes
    url: ghcr.io/intel/intel-resource-drivers-for-kubernetes
    oci: true

---

releases:
  - name: nvidia-device-plugin
    chart: nvdp/nvidia-device-plugin
    namespace: nvidia-device-plugin
    version: "0.19.3"
    cleanupOnFail: true
    createNamespace: true
    wait: true
    waitForJobs: true
    values:
      - gfd:
          enabled: true
        nfd:
          enabled: true
        runtimeClassName: nvidia
        deviceIDStrategy: index
  - name: intel-gpu-resource-driver
    chart: intel-resource-drivers-for-kubernetes/intel-gpu-resource-driver-chart
    namespace: intel-gpu-resource-driver
    version: "0.11.0"
    cleanupOnFail: true
    createNamespace: true
    wait: true
    waitForJobs: true
    values:
      - kubeletPlugin:
          privileged: true
          healthMonitoring:
            enabled: false