rancher:
  namespace: cattle-system
  enabled: true
  hostname: rancher
  replicas: 1
  # Disable default ingress
  ingress:
    enabled: false
  bootstrapPassword: todo

# Reset password  - kubectl --kubeconfig $KUBECONFIG -n cattle-system exec $(kubectl --kubeconfig $KUBECONFIG -n cattle-system get pods -l app=rancher --no-headers | head -1 | awk '{ print $1 }') -c rancher -- reset-password