apiVersion: v1
kind: Secret
metadata:
  name: tailscale-operator-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  client_id: {{ .Values.secured_client_id }}
  client_secret: {{ .Values.secured_client_secret }}
