apiVersion: v1
data:
    bootstrapPassword: TODO
kind: Secret
metadata:
    annotations:
        field.cattle.io/projectId: local:p-jfvwj
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "-5"
        helm.sh/resource-policy: keep
    name: bootstrap-secret
    namespace: cattle-system
type: Opaque
