name: Test Homelab

on: [push]

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v5
        with:
          version: "latest"
        id: install
      - name: Install helm-unittest

        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --verify=false

      - name: Lint charts
        run: make lint-helm
      - name: Test charts
        run: make test-helm
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.26
      - name: Run tests
        run: make test-go
